version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3309:33090"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraping
      MYSQL_USER: scraping
      MYSQL_PASSWORD: scraping
